---
surname: Mike Mahoney
address: "" # Subhead under name 
phone: 781-812-8842
www: mm218.dev
email: "mike.mahoney.218@gmail.com"
github: mikemahoney218
linkedin: mikemahoney218
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
docname: "Curriculum Vitae"
headcolor: 414141 #08004f
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
source("make_detailed_section.R")
```

# Education

```{r education}
PHD_ESF_Current <- vector("list")
PHD_ESF_Current$Details <- c("Doctor of Philosophy in Environmental Science (Area of Study: Coupled Natural and Human Systems)", 
                       "August 2020 - Present", 
                       "State University of New York College of Environmental 
                       Science and Forestry (SUNY-ESF)", 
                       "Syracuse, New York")
PHD_ESF_Current$Bullets <- NA

BS_ESF_18 <- vector("list")
BS_ESF_18$Details <- c("Bachelor of Science with Honors magna cum laude in 
                       Forest Ecosystem Science (GPA: 3.723)", 
                       "December 2018", 
                       "State University of New York College of Environmental 
                       Science and Forestry (SUNY-ESF)", 
                       "Syracuse, New York")
BS_ESF_18$Bullets <- c("Thesis: Beaver Foraging Preferences and Impacts on 
                       Forest Structure in New York’s Adirondack Mountains")

make_detailed_section(PHD_ESF_Current, order = 1:4)
make_detailed_section(BS_ESF_18, order = 1:4)
```

```{r eval=FALSE}
# Professional Appointments
# (tenure-track, instructorships, postdocs)
# Institution, department, title, year
```


# Publications

## In Review

```{r}
tribble(
  ~ When, ~ BeforeYou, ~ You, ~ AfterYou, ~ Title, ~ Details, ~ url,
  "2021", "", "Mahoney, M. J.,", "Johnson, J. K., Bevilacqua, E., and Beier, C. M. In Review.", "Ground noise filtering produces inferior models of forest aboveground biomass", "In review at Remote Sensing of Environment", "",
  "2021", "", "Mahoney, M. J.,", "Beier, C. M., and Ackerman, A. C. In Review.", "Interactive 3D visualizations of geospatial data using the terrainr R package.", "In review at International Journal of Digital Earth", ""
) %>% 
  brief_entries(glue::glue("<BeforeYou> \\textbf{<You>} <AfterYou> <Title> <Details> \\url{<url>}", 
                           .open = "<", 
                           .close = ">"), 
                When, 
                .protect = FALSE)
```

## Peer-Reviewed Publications

```{r}
tribble(
  ~ When, ~ BeforeYou, ~ You, ~ AfterYou, ~ Title, ~ Details, ~ url,
  "2020", "", "Mahoney, M. J.,", "and Stella, J. C. 2020.",
  "Stem size selectivity is stronger than species preferences for beaver, a central place forager.", 
  "Forest Ecology and Management 475 118331.", "https://doi.org/10.1016/j.foreco.2020.118331",
) %>% 
  brief_entries(glue::glue("<BeforeYou> \\textbf{<You>} <AfterYou> <Title> <Details> \\url{<url>}", 
                           .open = "<", 
                           .close = ">"), 
                When, 
                .protect = FALSE)
```

# Awards and Honors

```{r}
Awards <- tribble(
  ~ What, ~ When,
  "Robin Hood Oak Award for Academic Excellence", "2018",
  "Robert M. Hicks Award for Academic Achievement", "2018",
  "ESF Career Fellowship", "2018",
  "Outstanding Student Award for Accomplishments in Field Ecology and 
  Dendrology", "2017"
)

brief_entries(Awards, What, When)
```

```{r, eval=FALSE}
# Grants and Fellowships
# funder, institutional location recieved at, year span
```

# Invited Talks

```{r invited}
tribble(
  ~ When, ~ Title, ~ Details, ~ url,
  "2021", "Accessing the USGS National Map and making 3D maps with terrainr.", "Nell, C., Mahoney, M. J., and Platt, L. USGS Center for Data Integration, Lakewood, CO.", "",
  "2021", "terrainr: Landscape Visualizations Using Data from the National Map.", "Mahoney, M. J. USGS National Geospatial Technical Operations Center, Denver, CO.", "") %>% 
  brief_entries(glue::glue("\\textbf{<Title>} <Details> \\newline \\url{<url>}", 
                           .open = "<", 
                           .close = ">"), 
                When, 
                .protect = FALSE)
```

# Conference Activity

```{r, eval=FALSE}
# Subheadings: Panels Organized, Papers Presented, Discussant. 
# These entries will include: Name of paper, name of conference, date. 
# Future conferences SHOULD be listed here, if you have had a paper or panel officially accepted.
```

## Contributed Talks

```{r talks}
tribble(
  ~ When, ~ Title, ~ Details, ~ url,
  "2021", "Interactive 3D visualizations of environmental data using the terrainr R package.", "Mahoney, M. J., and Beier, C. M., and Ackerman, A. C. Paper presented at Visual Resources Stewardship Conference, Syracuse, NY.", "",
  "2018", "Beaver Foraging Preferences and Impacts on Forest Structure in the Adirondack Mountains of New York.", 
  "Mahoney, M. J., and Stella, J. C. Forest Ecosystem Monitoring Collective Conference, Burlington, VT.", "", 
  "2018","Beaver Foraging Preferences and Impacts on Forest Structure in the Adirondack Mountains of New York.", 
  "Mahoney, M. J., and Stella, J. C. Rochester Academy of Sciences Fall Scientific Paper Session, Geneseo, NY.", "") %>% 
  brief_entries(glue::glue("\\textbf{<Title>} <Details> \\newline \\url{<url>}", 
                           .open = "<", 
                           .close = ">"), 
                When, 
                .protect = FALSE)
```

\newpage{} 

## Poster Presentations

```{r}
tribble(
  ~ When, ~ Title, ~ Details, ~ url,
  "2019", "Nutritional Impacts on Invasive Beech Scale Quantification in Beech Bark Disease Aftermath Forests.", 
  "Dillon, G., Mahoney, M. J., Chase, S., and Johnston, M. New York Society of American Foresters Annual Meeting, Syracuse, NY.", "",
  "2018", "Impacts of Beaver on Forest Structure and Composition.", 
  "Mahoney, M. J., Zevin, R., and Stella, J.C. Spotlight on Student Research, Syracuse, NY.", "",
  "2018", "Impacts of Fertilization on Causal Organisms of Beech Bark Disease.", 
  "Mahoney, M. J., Leimanis, V., Desrochers, M. L., Giambona, B., Johnston, M. T., Yanai, R. D., and Dillon, G. A. Spotlight on Student Research, Syracuse, NY.", "",
  "2017", "An Investigation of Nutritional Effects on Beech Bark Disease Causal Organisms.", 
  "Lasser, G. A., Johnston, M., Mahoney, M., Leimanis, V., and Stoodley, J. Forest Ecosystem Monitoring Collective Conference, Burlington, VT.", "",
  "2017", "An Investigation of Nutritional Effects on Beech Bark Disease Causal Organisms.", 
  "Lasser, G. A., Johnston, M., Mahoney, M., Leimanis, V., and Stoodley, J. Poster session presented at the Rochester Academy of Sciences Fall Scientific Paper Session, Rochester, NY.", ""
) %>% 
  brief_entries(glue::glue("\\textbf{<Title>} <Details> \\newline \\url{<url>}", 
                           .open = "<", 
                           .close = ">"), 
                When, 
                .protect = FALSE)
```

```{r, eval=FALSE}
# Campus or Departmental Talks
# Invited to give within own department, on own campus
# No guest lectures, that's padding
```


# Teaching Experience

## Graduate Courses

```{r}
tribble(
  ~ When, ~ Title, ~ Role,
  "Fall 2021", "Machine Learning for Prediction: Concepts and Applications in R", "Instructor of Record"
) %>% 
  brief_entries(glue::glue("\\textbf{<Title>}. <Role>. <When>", 
                           .open = "<", 
                           .close = ">"),
                .protect = FALSE)
```

```{r, eval = FALSE}
# Research Experience. 
# RA experience goes here, as well as lab experience.  
# This is one location where slight elaboration is possible, 
# if the research was a team effort on a complex, multi-year theme.  
# One detailed sentence should suffice.  
```

# Research Experience

```{r research}
tribble(
  ~ When, ~ Lab, ~ Role,
  "2020-Present", "Climate And Applied Forest Research Institute, SUNY-ESF", "Research Assistant"
) %>% 
  brief_entries(glue::glue("\\textbf{<Lab>} \\newline{}<Role>", 
                           .open = "<", 
                           .close = ">"), 
                When, 
                .protect = FALSE)
```

```{r, eval = FALSE}
# Service To Profession. 
# Include journal manuscript review work (with journal titles 
# [mss. review CAN be given its own separate heading if you do a lot of this work]),
# leadership of professional organizations, etc. 
# Some people put panel organizing under service; check conventions in your field
```

```{r, eval=FALSE}
# Departmental/University Service. Include search committees and other committee work, appointments to Faculty Senate, etc.  Sorry to be a pain, but here the convention is that the Title or Committee is left justified, with the year in the entry.  Don’t ask me why, and only a convention, not a strict rule
```

```{r, eval = FALSE}
# Extracurricular University Service. [Optional. ] Can include involvement in student groups, sporting clubs, etc.
```

# Community Involvement and Outreach

```{r}
# Community Involvement/Outreach. [Optional.]  This includes work with libraries and schools, public lectures, etc.
tribble(
  ~ When, ~ Group, ~ Role, ~ Details,
  "2019-2020", "Code for Boston - Clean Slate Project.", 
  "Data Scientist and Project Manager (Volunteer)", 
  "Project working with Greater Boston Legal Society to advance criminal justice reform efforts."
) %>% 
  brief_entries(glue::glue(" \\textbf{<Group>} <Role>. \\newline{} <Details>",
                           .open = "<", 
                           .close = ">"), 
                When, 
                .protect = FALSE)
```

```{r, eval = FALSE}
# Media Coverage. [Optional.] Coverage of your work by the media.
```

# Software Development

```{r packages}
tribble(
  ~ Pkg, ~ When, ~ Role, ~ Details,
  "terrainr", "2021", "Lead developer", "Retrieve Data from the USGS National 
  Map and Transform it for 3D Landscape Visualizations.",
  "heddlr", "2020", "Lead developer", "Tools to enable functional programming 
  workflows for dynamic R Markdown document generation.",
  "spacey", "2020", "Lead developer", "USGS and ESRI data access for beautiful 
  landscape visualization."
) %>% 
  brief_entries(glue::glue("\\textbf{<Pkg>}: <Role> \\newline <Details>", 
                           .open = "<", 
                           .close = ">"), 
                When, 
                .protect = FALSE)
```

# Affiliations

```{r affiliations}
# Professional Memberships/Affiliations. 
# All professional organizations of which you are a member listed vertically. 
# Include years of joining when you are more senior and those years recede into the past—demonstrates length of commitment to a field.

tribble(
  ~ When, ~ What, ~Who,
  "2021 - Present", "The Carpentries", "Instructor in good standing"
) %>% 
  brief_entries(glue::glue("\\textbf{<What>}. <Who>", 
                           .open = "<", 
                           .close = ">"), 
                When, 
                .protect = FALSE)
```


```{r, eval=FALSE}
# References
# List references vertically. Give name and full title. 
# Do not refer to references as “Dr. xxx,” or “Professor xxx.” This makes you look like a graduate student. 
# Give full snail mail contact information along with tel and email. 
# To do otherwise is amateurish, even though we know nobody is going to use the snail mail address. 
# Do not give narrative verbiage or explanation of these references (ie, “Ph.D. Committee member,” etc.). 
# The only exception is a single reference that may be identified as “Teaching Reference.” This would be the fourth of four references.
```

