---
surname: Mike Mahoney
address: "" # Subhead under name 
phone: 781-812-8842
www: mm218.dev
email: "mike.mahoney.218@gmail.com"
github: mikemahoney218
linkedin: mikemahoney218
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::awesomecv:
    keep_tex: TRUE
docname: "Resume"
headcolor: 414141 #08004f
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
source("make_detailed_section.R")
```


# Work Experience
```{r}
## To reflect promotions, simply change the "with" and "where" arguments to "" -
## that'll keep everything grouped under the same header
RStudio_2022 <- vector("list")
RStudio_2022$Details <- c("Open Source Engineer", "May 2022 - August 2022", "Posit, PBC (Previously RStudio, PBC) - Internship", "Boston, MA (Remote)")
RStudio_2022$Bullets <- c(
  "Developed open-source packages for the R programming language, with a focus on enabling good practices in machine learning and statistical modeling.",
  "Designed and implemented the \"spatialsample\" package, providing utilities for spatial cross-validation; \"waywiser\", providing tools to assess spatial autocorrelation in model residuals, and implemented grouped resampling methods in the \"rsample\" package, the most requested feature in a package with more than 2 million total downloads.",
  "Wrote public-facing documentation to explain complex statistical and technical concepts to users from a wide variety of backgrounds, including articles on spatial buffers for spatial cross-validation, a general overview of cross-validation approaches for modeling purposes, and tutorials on how to use open-source tooling to assess models across multiple spatial scales.",
  "Implemented key computations in C++, speeding up package functionality by up to 50%."
  
  )

ESIP_2022 <- vector("list")
ESIP_2022$Details <- c("Community Fellow (Machine Learning)", "December 2021 - Present", "Federation of Earth Science Information Partners (ESIP) - Part Time", "Severna Park, MD (Remote)")
ESIP_2022$Bullets <- c(
  "Organized and assisted with monthly meetings of the ESIP Machine Learning cluster, an organization of Earth scientists from NASA, NOAA, USGS, and academic institutions.",
  "Assisted inter-agency focus group in setting priorities for the use of machine learning in Earth science across federal agencies, including both potential applications and best practices.", 
  "Assisted in organizing both the 2022 ESIP January Meeting and a conference session \"Advancing FAIRness and Fairness in AI/ML in the Geo-sciences\"."
  )

CAFRI_2020 <- vector("list")
CAFRI_2020$Details <- c("Research Assistant", "August 2020 - Present", "Climate and Applied Forest Research Institute - Academic Year", "Syracuse, NY")
CAFRI_2020$Bullets <- c(
  "Created R and Python-based spatial models of forest aboveground biomass as part of New York State's Climate Leadership and Community Protection Act. These models will, pending a current public comment period, be the method New York uses to track carbon sequestration in forests.",
  "Built cloud-based (AWS) data-delivery infrastructure to enable delivery of spatial data products to private and governmental partners, and to standardize data sharing practices across the Institute.",
  "Developed and taught \"Machine Learning Concepts and Applications\", a one-semester graduate course on applied machine learning for scientists."
  )

Wayfair_Analyst_June19 <- vector("list")
Wayfair_Analyst_June19$Details <- c("Analyst (Workforce Management - Forecasting & Analytics)", "June 2019 - August 2020", "Wayfair Inc. - Full Time", "Boston, Massachusetts")
Wayfair_Analyst_June19$Bullets <- c(
  "Developed and launched department's first automated streaming data pipelines, connecting BuildKite, Docker, R, Python and T-SQL in order to create always-up real-time dashboards of contact center production for customer service leadership team.",
  "Implemented process improvements including automating long-standing reporting (transforming monthly reporting into daily updates and increasing the accuracy of analytics) and introducing Git and related workflows to department.",
  "Demonstrated leadership as interdepartmental liaison between partner teams on matters of metric definitions, reporting methodologies, data availability, and data access.",
  "Served as department subject-matter expert on technical matters (including R, SQL, Git, and Docker) on projects ranging from automating analytics to developing CI/CD workflows.")

make_detailed_section(
  RStudio_2022,
  ESIP_2022,
  CAFRI_2020,
  Wayfair_Analyst_June19)
```

# Volunteer Positions

```{r}
Carpentries <- vector("list")
Carpentries$Details <- c("Curriculum Advisory Committee Member; Lesson Maintainer; Instructor", "2021-Present", "The Carpentries - Volunteer", "Remote")
Carpentries$Bullets <- c(
  "Committee member helping to advise the development of the complete geospatial curriculum of The Carpentries, a nonprofit dedicated to teaching researchers fundamental programming skills.",
  "Lesson maintainer for \"Introduction to R for Geospatial Data\", responsible for developing, improving, and responding to community feedback on an introductory R workshop for users focused on the skills necessary for working with geospatial data formats.",
  "Instructor responsible for organizing and leading free programming workshops for early career researchers.")

make_detailed_section(Carpentries)
```

```{r}
# Additional Information
TechnicalSkills <- vector("list")
TechnicalSkills$Details <- c("Technical Skills", NA, NA, NA)
TechnicalSkills$Bullets <- c(
  "Proficient in R, Python, SQL, SAS, and Linux shell languages, and combining these tools to solve multifaceted data science problems",
  "Five years of experience with spatial analysis and popular GIS tooling, including ArcGIS, QGIS, and the R spatial ecosystem",
  "Lead developer of terrainr, an R package released as part of the rOpenSci project")

#make_detailed_section(TechnicalSkills)
```

# Education

```{r education}
PHD_ESF_Current <- vector("list")
PHD_ESF_Current$Details <- c("Doctor of Philosophy in Environmental Science (Area of Study: Coupled Natural and Human Systems)", 
                       "August 2020 - Present", 
                       "State University of New York College of Environmental 
                       Science and Forestry (SUNY-ESF)", 
                       "Syracuse, New York")
PHD_ESF_Current$Bullets <- c(
  "Dissertation: Being There? The Use of Immersive Virtual Environments to Replicate Real-World Experiences in Nature",
  "Awards: New York State GIS Association Application Award (2021)"
)

make_detailed_section(PHD_ESF_Current, order = 1:4)
```
